spring.application.name=GKPS
#spring.data.mongodb.uri=${MONGODB_URI}

spring.data.mongodb.uri=mongodb://localhost:27017/gkps

#logging
logging.level.root=INFO
logging.level.com.gkps=DEBUG
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

#agar field null tetap terlihat
spring.jackson.default-property-inclusion=NON_NULL
spring.jackson.serialization.fail-on-empty-beans=false


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration